# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slave.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slave.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bslave.proto\"\"\n\x04Wieg\x12\x0c\n\x04size\x18\x01 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\"\xb7\x01\n\x0bResponseAll\x12\x11\n\tPORTA_IDR\x18\x01 \x01(\r\x12\x11\n\tPORTB_IDR\x18\x02 \x01(\r\x12\x11\n\tPORTA_ODR\x18\x03 \x01(\r\x12\x11\n\tPORTB_ODR\x18\x04 \x01(\r\x12\x12\n\nRELAYS_IDR\x18\x05 \x01(\r\x12\x12\n\nRELAYS_ODR\x18\x06 \x01(\r\x12\x19\n\nWiegandCh1\x18\x07 \x01(\x0b\x32\x05.Wieg\x12\x19\n\nWiegandCh2\x18\x08 \x01(\x0b\x32\x05.Wieg\"2\n\x05Pulse\x12\x0b\n\x03pin\x18\x01 \x02(\r\x12\r\n\x05width\x18\x02 \x02(\r\x12\r\n\x05\x64\x65lay\x18\x03 \x01(\r')
)




_WIEG = _descriptor.Descriptor(
  name='Wieg',
  full_name='Wieg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='Wieg.size', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Wieg.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=49,
)


_RESPONSEALL = _descriptor.Descriptor(
  name='ResponseAll',
  full_name='ResponseAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PORTA_IDR', full_name='ResponseAll.PORTA_IDR', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PORTB_IDR', full_name='ResponseAll.PORTB_IDR', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PORTA_ODR', full_name='ResponseAll.PORTA_ODR', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PORTB_ODR', full_name='ResponseAll.PORTB_ODR', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RELAYS_IDR', full_name='ResponseAll.RELAYS_IDR', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RELAYS_ODR', full_name='ResponseAll.RELAYS_ODR', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WiegandCh1', full_name='ResponseAll.WiegandCh1', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WiegandCh2', full_name='ResponseAll.WiegandCh2', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=235,
)


_PULSE = _descriptor.Descriptor(
  name='Pulse',
  full_name='Pulse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin', full_name='Pulse.pin', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='Pulse.width', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delay', full_name='Pulse.delay', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=287,
)

_RESPONSEALL.fields_by_name['WiegandCh1'].message_type = _WIEG
_RESPONSEALL.fields_by_name['WiegandCh2'].message_type = _WIEG
DESCRIPTOR.message_types_by_name['Wieg'] = _WIEG
DESCRIPTOR.message_types_by_name['ResponseAll'] = _RESPONSEALL
DESCRIPTOR.message_types_by_name['Pulse'] = _PULSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Wieg = _reflection.GeneratedProtocolMessageType('Wieg', (_message.Message,), dict(
  DESCRIPTOR = _WIEG,
  __module__ = 'slave_pb2'
  # @@protoc_insertion_point(class_scope:Wieg)
  ))
_sym_db.RegisterMessage(Wieg)

ResponseAll = _reflection.GeneratedProtocolMessageType('ResponseAll', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEALL,
  __module__ = 'slave_pb2'
  # @@protoc_insertion_point(class_scope:ResponseAll)
  ))
_sym_db.RegisterMessage(ResponseAll)

Pulse = _reflection.GeneratedProtocolMessageType('Pulse', (_message.Message,), dict(
  DESCRIPTOR = _PULSE,
  __module__ = 'slave_pb2'
  # @@protoc_insertion_point(class_scope:Pulse)
  ))
_sym_db.RegisterMessage(Pulse)


# @@protoc_insertion_point(module_scope)
